spring:
  application:
    name: monitor-server
  cloud:
    stream:
      bindings:
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.process.run
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.process.run
          group: monitorRunGroup

monitor:
  execution-env-name: ${MONITOR_EXECUTION_ENV_NAME:default-env}

powsybl-ws:
  database:
    queryBegin: '&'
    customQuery: ${powsybl-ws.database.customQueryBegin}reWriteBatchedInserts=true
    name: monitor