spring:
  application:
    name: monitor-server
  cloud:
    stream:
      bindings:
        publishRunSecurityAnalysis-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.process.securityanalysis.run
        publishRunLoadFlow-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.process.loadflow.run
        publishMonitorUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.update
        consumeMonitorWorkerUpdate-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.worker.update
          group: monitorWorkerUpdateGroup

powsybl-ws:
  database:
    queryBegin: '&'
    customQuery: ${powsybl-ws.database.customQueryBegin}reWriteBatchedInserts=true
    name: monitor